"""Membangun laporan Markdown dari data rekap."""

def build_markdown_report(records):
    header = "# Rekap Nilai Mahasiswa\n\n"
    header += "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |\n"
    header += "|---|---|---:|---:|:---:|\n"
    lines = [header]
    for r in records:
        lines.append(f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f} | {r['nilai_akhir']:.2f} | {r['predikat']} |")
    lines.append("\nGenerated by student_performance_tracker")
    return "\n".join(lines)

def save_text(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
